FROM flink:1.18-scala_2.12

USER root

COPY lib/*.jar /opt/flink/lib/

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev \
    && rm -rf /var/lib/apt/lists/* \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && pip3 install --no-cache-dir --upgrade pip setuptools wheel \
    && pip3 install --no-cache-dir apache-flink==1.18.1 \
    && chown -R flink:flink /opt/flink/lib

USER flink